<style>
	.view-icons label {
		display: inline-block;
		width: 300px;
		font-size: 20px;
		margin-bottom: 5px;
	}
	.view-icons span {
		margin: 5px;
	}
</style>
<template>
<div>
	<h3> Photon Icons </h3>
	<div class="view-icons">
<!-- start -->
<label title="\e800"><i class="pt-note"></i><span>pt-note</span></label>
<label title="\e801"><i class="pt-note-beamed"></i><span>pt-note-beamed</span></label>
<label title="\e802"><i class="pt-music"></i><span>pt-music</span></label>
<label title="\e803"><i class="pt-search"></i><span>pt-search</span></label>
<label title="\e804"><i class="pt-flashlight"></i><span>pt-flashlight</span></label>
<label title="\e805"><i class="pt-mail"></i><span>pt-mail</span></label>
<label title="\e806"><i class="pt-heart"></i><span>pt-heart</span></label>
<label title="\e807"><i class="pt-heart-empty"></i><span>pt-heart-empty</span></label>
<label title="\e808"><i class="pt-star"></i><span>pt-star</span></label>
<label title="\e809"><i class="pt-star-empty"></i><span>pt-star-empty</span></label>
<label title="\e80a"><i class="pt-user"></i><span>pt-user</span></label>
<label title="\e80b"><i class="pt-users"></i><span>pt-users</span></label>
<label title="\e80c"><i class="pt-user-add"></i><span>pt-user-add</span></label>
<label title="\e80d"><i class="pt-video"></i><span>pt-video</span></label>
<label title="\e80e"><i class="pt-picture"></i><span>pt-picture</span></label>
<label title="\e80f"><i class="pt-camera"></i><span>pt-camera</span></label>
<label title="\e810"><i class="pt-layout"></i><span>pt-layout</span></label>
<label title="\e811"><i class="pt-menu"></i><span>pt-menu</span></label>
<label title="\e812"><i class="pt-check"></i><span>pt-check</span></label>
<label title="\e813"><i class="pt-cancel"></i><span>pt-cancel</span></label>
<label title="\e814"><i class="pt-cancel-circled"></i><span>pt-cancel-circled</span></label>
<label title="\e815"><i class="pt-cancel-squared"></i><span>pt-cancel-squared</span></label>
<label title="\e816"><i class="pt-plus"></i><span>pt-plus</span></label>
<label title="\e817"><i class="pt-plus-circled"></i><span>pt-plus-circled</span></label>
<label title="\e818"><i class="pt-plus-squared"></i><span>pt-plus-squared</span></label>
<label title="\e819"><i class="pt-minus"></i><span>pt-minus</span></label>
<label title="\e81a"><i class="pt-minus-circled"></i><span>pt-minus-circled</span></label>
<label title="\e81b"><i class="pt-minus-squared"></i><span>pt-minus-squared</span></label>
<label title="\e81c"><i class="pt-help"></i><span>pt-help</span></label>
<label title="\e81d"><i class="pt-help-circled"></i><span>pt-help-circled</span></label>
<label title="\e81e"><i class="pt-info"></i><span>pt-info</span></label>
<label title="\e81f"><i class="pt-info-circled"></i><span>pt-info-circled</span></label>
<label title="\e820"><i class="pt-back"></i><span>pt-back</span></label>
<label title="\e821"><i class="pt-home"></i><span>pt-home</span></label>
<label title="\e822"><i class="pt-link"></i><span>pt-link</span></label>
<label title="\e823"><i class="pt-attach"></i><span>pt-attach</span></label>
<label title="\e824"><i class="pt-lock"></i><span>pt-lock</span></label>
<label title="\e825"><i class="pt-lock-open"></i><span>pt-lock-open</span></label>
<label title="\e826"><i class="pt-eye"></i><span>pt-eye</span></label>
<label title="\e827"><i class="pt-tag"></i><span>pt-tag</span></label>
<label title="\e828"><i class="pt-bookmark"></i><span>pt-bookmark</span></label>
<label title="\e829"><i class="pt-bookmarks"></i><span>pt-bookmarks</span></label>
<label title="\e82a"><i class="pt-flag"></i><span>pt-flag</span></label>
<label title="\e82b"><i class="pt-thumbs-up"></i><span>pt-thumbs-up</span></label>
<label title="\e82c"><i class="pt-thumbs-down"></i><span>pt-thumbs-down</span></label>
<label title="\e82d"><i class="pt-download"></i><span>pt-download</span></label>
<label title="\e82e"><i class="pt-upload"></i><span>pt-upload</span></label>
<label title="\e82f"><i class="pt-upload-cloud"></i><span>pt-upload-cloud</span></label>
<label title="\e830"><i class="pt-reply"></i><span>pt-reply</span></label>
<label title="\e831"><i class="pt-reply-all"></i><span>pt-reply-all</span></label>
<label title="\e832"><i class="pt-forward"></i><span>pt-forward</span></label>
<label title="\e833"><i class="pt-quote"></i><span>pt-quote</span></label>
<label title="\e834"><i class="pt-code"></i><span>pt-code</span></label>
<label title="\e835"><i class="pt-export"></i><span>pt-export</span></label>
<label title="\e836"><i class="pt-pencil"></i><span>pt-pencil</span></label>
<label title="\e837"><i class="pt-feather"></i><span>pt-feather</span></label>
<label title="\e838"><i class="pt-print"></i><span>pt-print</span></label>
<label title="\e839"><i class="pt-retweet"></i><span>pt-retweet</span></label>
<label title="\e83a"><i class="pt-keyboard"></i><span>pt-keyboard</span></label>
<label title="\e83b"><i class="pt-comment"></i><span>pt-comment</span></label>
<label title="\e83c"><i class="pt-chat"></i><span>pt-chat</span></label>
<label title="\e83d"><i class="pt-bell"></i><span>pt-bell</span></label>
<label title="\e83e"><i class="pt-attention"></i><span>pt-attention</span></label>
<label title="\e83f"><i class="pt-alert"></i><span>pt-alert</span></label>
<label title="\e840"><i class="pt-vcard"></i><span>pt-vcard</span></label>
<label title="\e841"><i class="pt-address"></i><span>pt-address</span></label>
<label title="\e842"><i class="pt-location"></i><span>pt-location</span></label>
<label title="\e843"><i class="pt-map"></i><span>pt-map</span></label>
<label title="\e844"><i class="pt-direction"></i><span>pt-direction</span></label>
<label title="\e845"><i class="pt-compass"></i><span>pt-compass</span></label>
<label title="\e846"><i class="pt-cup"></i><span>pt-cup</span></label>
<label title="\e847"><i class="pt-trash"></i><span>pt-trash</span></label>
<label title="\e848"><i class="pt-doc"></i><span>pt-doc</span></label>
<label title="\e849"><i class="pt-docs"></i><span>pt-docs</span></label>
<label title="\e84a"><i class="pt-doc-landscape"></i><span>pt-doc-landscape</span></label>
<label title="\e84b"><i class="pt-doc-text"></i><span>pt-doc-text</span></label>
<label title="\e84c"><i class="pt-doc-text-inv"></i><span>pt-doc-text-inv</span></label>
<label title="\e84d"><i class="pt-newspaper"></i><span>pt-newspaper</span></label>
<label title="\e84e"><i class="pt-book-open"></i><span>pt-book-open</span></label>
<label title="\e84f"><i class="pt-book"></i><span>pt-book</span></label>
<label title="\e850"><i class="pt-folder"></i><span>pt-folder</span></label>
<label title="\e851"><i class="pt-archive"></i><span>pt-archive</span></label>
<label title="\e852"><i class="pt-box"></i><span>pt-box</span></label>
<label title="\e853"><i class="pt-rss"></i><span>pt-rss</span></label>
<label title="\e854"><i class="pt-phone"></i><span>pt-phone</span></label>
<label title="\e855"><i class="pt-cog"></i><span>pt-cog</span></label>
<label title="\e856"><i class="pt-tools"></i><span>pt-tools</span></label>
<label title="\e857"><i class="pt-share"></i><span>pt-share</span></label>
<label title="\e858"><i class="pt-shareable"></i><span>pt-shareable</span></label>
<label title="\e859"><i class="pt-basket"></i><span>pt-basket</span></label>
<label title="\e85a"><i class="pt-bag"></i><span>pt-bag</span></label>
<label title="\e85b"><i class="pt-calendar"></i><span>pt-calendar</span></label>
<label title="\e85c"><i class="pt-login"></i><span>pt-login</span></label>
<label title="\e85d"><i class="pt-logout"></i><span>pt-logout</span></label>
<label title="\e85e"><i class="pt-mic"></i><span>pt-mic</span></label>
<label title="\e85f"><i class="pt-mute"></i><span>pt-mute</span></label>
<label title="\e860"><i class="pt-sound"></i><span>pt-sound</span></label>
<label title="\e861"><i class="pt-volume"></i><span>pt-volume</span></label>
<label title="\e862"><i class="pt-clock"></i><span>pt-clock</span></label>
<label title="\e863"><i class="pt-hourglass"></i><span>pt-hourglass</span></label>
<label title="\e864"><i class="pt-lamp"></i><span>pt-lamp</span></label>
<label title="\e865"><i class="pt-light-down"></i><span>pt-light-down</span></label>
<label title="\e866"><i class="pt-light-up"></i><span>pt-light-up</span></label>
<label title="\e867"><i class="pt-adjust"></i><span>pt-adjust</span></label>
<label title="\e868"><i class="pt-block"></i><span>pt-block</span></label>
<label title="\e869"><i class="pt-resize-full"></i><span>pt-resize-full</span></label>
<label title="\e86a"><i class="pt-resize-small"></i><span>pt-resize-small</span></label>
<label title="\e86b"><i class="pt-popup"></i><span>pt-popup</span></label>
<label title="\e86c"><i class="pt-publish"></i><span>pt-publish</span></label>
<label title="\e86d"><i class="pt-window"></i><span>pt-window</span></label>
<label title="\e86e"><i class="pt-arrow-combo"></i><span>pt-arrow-combo</span></label>
<label title="\e86f"><i class="pt-down-circled"></i><span>pt-down-circled</span></label>
<label title="\e870"><i class="pt-left-circled"></i><span>pt-left-circled</span></label>
<label title="\e871"><i class="pt-right-circled"></i><span>pt-right-circled</span></label>
<label title="\e872"><i class="pt-up-circled"></i><span>pt-up-circled</span></label>
<label title="\e873"><i class="pt-down-open"></i><span>pt-down-open</span></label>
<label title="\e874"><i class="pt-left-open"></i><span>pt-left-open</span></label>
<label title="\e875"><i class="pt-right-open"></i><span>pt-right-open</span></label>
<label title="\e876"><i class="pt-up-open"></i><span>pt-up-open</span></label>
<label title="\e877"><i class="pt-down-open-mini"></i><span>pt-down-open-mini</span></label>
<label title="\e878"><i class="pt-left-open-mini"></i><span>pt-left-open-mini</span></label>
<label title="\e879"><i class="pt-right-open-mini"></i><span>pt-right-open-mini</span></label>
<label title="\e87a"><i class="pt-up-open-mini"></i><span>pt-up-open-mini</span></label>
<label title="\e87b"><i class="pt-down-open-big"></i><span>pt-down-open-big</span></label>
<label title="\e87c"><i class="pt-left-open-big"></i><span>pt-left-open-big</span></label>
<label title="\e87d"><i class="pt-right-open-big"></i><span>pt-right-open-big</span></label>
<label title="\e87e"><i class="pt-up-open-big"></i><span>pt-up-open-big</span></label>
<label title="\e87f"><i class="pt-down"></i><span>pt-down</span></label>
<label title="\e880"><i class="pt-left"></i><span>pt-left</span></label>
<label title="\e881"><i class="pt-right"></i><span>pt-right</span></label>
<label title="\e882"><i class="pt-up"></i><span>pt-up</span></label>
<label title="\e883"><i class="pt-down-dir"></i><span>pt-down-dir</span></label>
<label title="\e884"><i class="pt-left-dir"></i><span>pt-left-dir</span></label>
<label title="\e885"><i class="pt-right-dir"></i><span>pt-right-dir</span></label>
<label title="\e886"><i class="pt-up-dir"></i><span>pt-up-dir</span></label>
<label title="\e887"><i class="pt-down-bold"></i><span>pt-down-bold</span></label>
<label title="\e888"><i class="pt-left-bold"></i><span>pt-left-bold</span></label>
<label title="\e889"><i class="pt-right-bold"></i><span>pt-right-bold</span></label>
<label title="\e88a"><i class="pt-up-bold"></i><span>pt-up-bold</span></label>
<label title="\e88b"><i class="pt-down-thin"></i><span>pt-down-thin</span></label>
<label title="\e88c"><i class="pt-left-thin"></i><span>pt-left-thin</span></label>
<label title="\e88d"><i class="pt-right-thin"></i><span>pt-right-thin</span></label>
<label title="\e88e"><i class="pt-up-thin"></i><span>pt-up-thin</span></label>
<label title="\e88f"><i class="pt-ccw"></i><span>pt-ccw</span></label>
<label title="\e890"><i class="pt-cw"></i><span>pt-cw</span></label>
<label title="\e891"><i class="pt-arrows-ccw"></i><span>pt-arrows-ccw</span></label>
<label title="\e892"><i class="pt-level-down"></i><span>pt-level-down</span></label>
<label title="\e893"><i class="pt-level-up"></i><span>pt-level-up</span></label>
<label title="\e894"><i class="pt-shuffle"></i><span>pt-shuffle</span></label>
<label title="\e895"><i class="pt-loop"></i><span>pt-loop</span></label>
<label title="\e896"><i class="pt-switch"></i><span>pt-switch</span></label>
<label title="\e897"><i class="pt-play"></i><span>pt-play</span></label>
<label title="\e898"><i class="pt-stop"></i><span>pt-stop</span></label>
<label title="\e899"><i class="pt-pause"></i><span>pt-pause</span></label>
<label title="\e89a"><i class="pt-record"></i><span>pt-record</span></label>
<label title="\e89b"><i class="pt-to-end"></i><span>pt-to-end</span></label>
<label title="\e89c"><i class="pt-to-start"></i><span>pt-to-start</span></label>
<label title="\e89d"><i class="pt-fast-forward"></i><span>pt-fast-forward</span></label>
<label title="\e89e"><i class="pt-fast-backward"></i><span>pt-fast-backward</span></label>
<label title="\e89f"><i class="pt-progress-0"></i><span>pt-progress-0</span></label>
<label title="\e8a0"><i class="pt-progress-1"></i><span>pt-progress-1</span></label>
<label title="\e8a1"><i class="pt-progress-2"></i><span>pt-progress-2</span></label>
<label title="\e8a2"><i class="pt-progress-3"></i><span>pt-progress-3</span></label>
<label title="\e8a3"><i class="pt-target"></i><span>pt-target</span></label>
<label title="\e8a4"><i class="pt-palette"></i><span>pt-palette</span></label>
<label title="\e8a5"><i class="pt-list"></i><span>pt-list</span></label>
<label title="\e8a6"><i class="pt-list-add"></i><span>pt-list-add</span></label>
<label title="\e8a7"><i class="pt-signal"></i><span>pt-signal</span></label>
<label title="\e8a8"><i class="pt-trophy"></i><span>pt-trophy</span></label>
<label title="\e8a9"><i class="pt-battery"></i><span>pt-battery</span></label>
<label title="\e8aa"><i class="pt-back-in-time"></i><span>pt-back-in-time</span></label>
<label title="\e8ab"><i class="pt-monitor"></i><span>pt-monitor</span></label>
<label title="\e8ac"><i class="pt-mobile"></i><span>pt-mobile</span></label>
<label title="\e8ad"><i class="pt-network"></i><span>pt-network</span></label>
<label title="\e8ae"><i class="pt-cd"></i><span>pt-cd</span></label>
<label title="\e8af"><i class="pt-inbox"></i><span>pt-inbox</span></label>
<label title="\e8b0"><i class="pt-install"></i><span>pt-install</span></label>
<label title="\e8b1"><i class="pt-globe"></i><span>pt-globe</span></label>
<label title="\e8b2"><i class="pt-cloud"></i><span>pt-cloud</span></label>
<label title="\e8b3"><i class="pt-cloud-thunder"></i><span>pt-cloud-thunder</span></label>
<label title="\e8b4"><i class="pt-flash"></i><span>pt-flash</span></label>
<label title="\e8b5"><i class="pt-moon"></i><span>pt-moon</span></label>
<label title="\e8b6"><i class="pt-flight"></i><span>pt-flight</span></label>
<label title="\e8b7"><i class="pt-paper-plane"></i><span>pt-paper-plane</span></label>
<label title="\e8b8"><i class="pt-leaf"></i><span>pt-leaf</span></label>
<label title="\e8b9"><i class="pt-lifebuoy"></i><span>pt-lifebuoy</span></label>
<label title="\e8ba"><i class="pt-mouse"></i><span>pt-mouse</span></label>
<label title="\e8bb"><i class="pt-briefcase"></i><span>pt-briefcase</span></label>
<label title="\e8bc"><i class="pt-suitcase"></i><span>pt-suitcase</span></label>
<label title="\e8bd"><i class="pt-dot"></i><span>pt-dot</span></label>
<label title="\e8be"><i class="pt-dot-2"></i><span>pt-dot-2</span></label>
<label title="\e8bf"><i class="pt-dot-3"></i><span>pt-dot-3</span></label>
<label title="\e8c0"><i class="pt-brush"></i><span>pt-brush</span></label>
<label title="\e8c1"><i class="pt-magnet"></i><span>pt-magnet</span></label>
<label title="\e8c2"><i class="pt-infinity"></i><span>pt-infinity</span></label>
<label title="\e8c3"><i class="pt-erase"></i><span>pt-erase</span></label>
<label title="\e8c4"><i class="pt-chart-pie"></i><span>pt-chart-pie</span></label>
<label title="\e8c5"><i class="pt-chart-line"></i><span>pt-chart-line</span></label>
<label title="\e8c6"><i class="pt-chart-bar"></i><span>pt-chart-bar</span></label>
<label title="\e8c7"><i class="pt-chart-area"></i><span>pt-chart-area</span></label>
<label title="\e8c8"><i class="pt-tape"></i><span>pt-tape</span></label>
<label title="\e8c9"><i class="pt-graduation-cap"></i><span>pt-graduation-cap</span></label>
<label title="\e8ca"><i class="pt-language"></i><span>pt-language</span></label>
<label title="\e8cb"><i class="pt-ticket"></i><span>pt-ticket</span></label>
<label title="\e8cc"><i class="pt-water"></i><span>pt-water</span></label>
<label title="\e8cd"><i class="pt-droplet"></i><span>pt-droplet</span></label>
<label title="\e8ce"><i class="pt-air"></i><span>pt-air</span></label>
<label title="\e8cf"><i class="pt-credit-card"></i><span>pt-credit-card</span></label>
<label title="\e8d0"><i class="pt-floppy"></i><span>pt-floppy</span></label>
<label title="\e8d1"><i class="pt-clipboard"></i><span>pt-clipboard</span></label>
<label title="\e8d2"><i class="pt-megaphone"></i><span>pt-megaphone</span></label>
<label title="\e8d3"><i class="pt-database"></i><span>pt-database</span></label>
<label title="\e8d4"><i class="pt-drive"></i><span>pt-drive</span></label>
<label title="\e8d5"><i class="pt-bucket"></i><span>pt-bucket</span></label>
<label title="\e8d6"><i class="pt-thermometer"></i><span>pt-thermometer</span></label>
<label title="\e8d7"><i class="pt-key"></i><span>pt-key</span></label>
<label title="\e8d8"><i class="pt-flow-cascade"></i><span>pt-flow-cascade</span></label>
<label title="\e8d9"><i class="pt-flow-branch"></i><span>pt-flow-branch</span></label>
<label title="\e8da"><i class="pt-flow-tree"></i><span>pt-flow-tree</span></label>
<label title="\e8db"><i class="pt-flow-line"></i><span>pt-flow-line</span></label>
<label title="\e8dc"><i class="pt-flow-parallel"></i><span>pt-flow-parallel</span></label>
<label title="\e8dd"><i class="pt-rocket"></i><span>pt-rocket</span></label>
<label title="\e8de"><i class="pt-gauge"></i><span>pt-gauge</span></label>
<label title="\e8df"><i class="pt-traffic-cone"></i><span>pt-traffic-cone</span></label>
<label title="\e8e0"><i class="pt-cc"></i><span>pt-cc</span></label>
<label title="\e8e1"><i class="pt-cc-by"></i><span>pt-cc-by</span></label>
<label title="\e8e2"><i class="pt-cc-nc"></i><span>pt-cc-nc</span></label>
<label title="\e8e3"><i class="pt-cc-nc-eu"></i><span>pt-cc-nc-eu</span></label>
<label title="\e8e4"><i class="pt-cc-nc-jp"></i><span>pt-cc-nc-jp</span></label>
<label title="\e8e5"><i class="pt-cc-sa"></i><span>pt-cc-sa</span></label>
<label title="\e8e6"><i class="pt-cc-nd"></i><span>pt-cc-nd</span></label>
<label title="\e8e7"><i class="pt-cc-pd"></i><span>pt-cc-pd</span></label>
<label title="\e8e8"><i class="pt-cc-zero"></i><span>pt-cc-zero</span></label>
<label title="\e8e9"><i class="pt-cc-share"></i><span>pt-cc-share</span></label>
<label title="\e8ea"><i class="pt-cc-remix"></i><span>pt-cc-remix</span></label>
<label title="\e8eb"><i class="pt-github"></i><span>pt-github</span></label>
<label title="\e8ec"><i class="pt-github-circled"></i><span>pt-github-circled</span></label>
<label title="\e8ed"><i class="pt-flickr"></i><span>pt-flickr</span></label>
<label title="\e8ee"><i class="pt-flickr-circled"></i><span>pt-flickr-circled</span></label>
<label title="\e8ef"><i class="pt-vimeo"></i><span>pt-vimeo</span></label>
<label title="\e8f0"><i class="pt-vimeo-circled"></i><span>pt-vimeo-circled</span></label>
<label title="\e8f1"><i class="pt-twitter"></i><span>pt-twitter</span></label>
<label title="\e8f2"><i class="pt-twitter-circled"></i><span>pt-twitter-circled</span></label>
<label title="\e8f3"><i class="pt-facebook"></i><span>pt-facebook</span></label>
<label title="\e8f4"><i class="pt-facebook-circled"></i><span>pt-facebook-circled</span></label>
<label title="\e8f5"><i class="pt-facebook-squared"></i><span>pt-facebook-squared</span></label>
<label title="\e8f6"><i class="pt-gplus"></i><span>pt-gplus</span></label>
<label title="\e8f7"><i class="pt-gplus-circled"></i><span>pt-gplus-circled</span></label>
<label title="\e8f8"><i class="pt-pinterest"></i><span>pt-pinterest</span></label>
<label title="\e8f9"><i class="pt-pinterest-circled"></i><span>pt-pinterest-circled</span></label>
<label title="\e8fa"><i class="pt-tumblr"></i><span>pt-tumblr</span></label>
<label title="\e8fb"><i class="pt-tumblr-circled"></i><span>pt-tumblr-circled</span></label>
<label title="\e8fc"><i class="pt-linkedin"></i><span>pt-linkedin</span></label>
<label title="\e8fd"><i class="pt-linkedin-circled"></i><span>pt-linkedin-circled</span></label>
<label title="\e8fe"><i class="pt-dribbble"></i><span>pt-dribbble</span></label>
<label title="\e8ff"><i class="pt-dribbble-circled"></i><span>pt-dribbble-circled</span></label>
<label title="\e900"><i class="pt-stumbleupon"></i><span>pt-stumbleupon</span></label>
<label title="\e901"><i class="pt-stumbleupon-circled"></i><span>pt-stumbleupon-circled</span></label>
<label title="\e902"><i class="pt-lastfm"></i><span>pt-lastfm</span></label>
<label title="\e903"><i class="pt-lastfm-circled"></i><span>pt-lastfm-circled</span></label>
<label title="\e904"><i class="pt-rdio"></i><span>pt-rdio</span></label>
<label title="\e905"><i class="pt-rdio-circled"></i><span>pt-rdio-circled</span></label>
<label title="\e906"><i class="pt-spotify"></i><span>pt-spotify</span></label>
<label title="\e907"><i class="pt-spotify-circled"></i><span>pt-spotify-circled</span></label>
<label title="\e908"><i class="pt-qq"></i><span>pt-qq</span></label>
<label title="\e909"><i class="pt-instagram"></i><span>pt-instagram</span></label>
<label title="\e90a"><i class="pt-dropbox"></i><span>pt-dropbox</span></label>
<label title="\e90b"><i class="pt-evernote"></i><span>pt-evernote</span></label>
<label title="\e90c"><i class="pt-flattr"></i><span>pt-flattr</span></label>
<label title="\e90d"><i class="pt-skype"></i><span>pt-skype</span></label>
<label title="\e90e"><i class="pt-skype-circled"></i><span>pt-skype-circled</span></label>
<label title="\e90f"><i class="pt-renren"></i><span>pt-renren</span></label>
<label title="\e910"><i class="pt-sina-weibo"></i><span>pt-sina-weibo</span></label>
<label title="\e911"><i class="pt-paypal"></i><span>pt-paypal</span></label>
<label title="\e912"><i class="pt-picasa"></i><span>pt-picasa</span></label>
<label title="\e913"><i class="pt-soundcloud"></i><span>pt-soundcloud</span></label>
<label title="\e914"><i class="pt-mixi"></i><span>pt-mixi</span></label>
<label title="\e915"><i class="pt-behance"></i><span>pt-behance</span></label>
<label title="\e916"><i class="pt-google-circles"></i><span>pt-google-circles</span></label>
<label title="\e917"><i class="pt-vkontakte"></i><span>pt-vkontakte</span></label>
<label title="\e918"><i class="pt-smashing"></i><span>pt-smashing</span></label>
<label title="\e919"><i class="pt-sweden"></i><span>pt-sweden</span></label>
<label title="\e91a"><i class="pt-db-shape"></i><span>pt-db-shape</span></label>
<label title="\e91b"><i class="pt-logo-db"></i><span>pt-logo-db</span></label>

<!-- end -->
	</div>
</div>
</template>