<style>
	.view-icons label {
		display: inline-block;
		width: 300px;
		font-size: 20px;
		margin-bottom: 5px;
	}
	.view-icons span {
		margin: 5px;
	}
</style>
<template>
<div>
	<h3> Fontawesome Icons </h3>
	<div class="view-icons">
<!-- start -->
<label title="\f000"><i class="fa-glass"></i><span>fa-glass</span></label>
<label title="\f001"><i class="fa-music"></i><span>fa-music</span></label>
<label title="\f002"><i class="fa-search"></i><span>fa-search</span></label>
<label title="\f003"><i class="fa-envelope-o"></i><span>fa-envelope-o</span></label>
<label title="\f004"><i class="fa-heart"></i><span>fa-heart</span></label>
<label title="\f005"><i class="fa-star"></i><span>fa-star</span></label>
<label title="\f006"><i class="fa-star-o"></i><span>fa-star-o</span></label>
<label title="\f007"><i class="fa-user"></i><span>fa-user</span></label>
<label title="\f008"><i class="fa-film"></i><span>fa-film</span></label>
<label title="\f009"><i class="fa-th-large"></i><span>fa-th-large</span></label>
<label title="\f00a"><i class="fa-th"></i><span>fa-th</span></label>
<label title="\f00b"><i class="fa-th-list"></i><span>fa-th-list</span></label>
<label title="\f00c"><i class="fa-check"></i><span>fa-check</span></label>
<label title="\f00d"><i class="fa-times"></i><span>fa-times</span></label>
<label title="\f00e"><i class="fa-search-plus"></i><span>fa-search-plus</span></label>
<label title="\f010"><i class="fa-search-minus"></i><span>fa-search-minus</span></label>
<label title="\f011"><i class="fa-power-off"></i><span>fa-power-off</span></label>
<label title="\f012"><i class="fa-signal"></i><span>fa-signal</span></label>
<label title="\f013"><i class="fa-cog"></i><span>fa-cog</span></label>
<label title="\f014"><i class="fa-trash-o"></i><span>fa-trash-o</span></label>
<label title="\f015"><i class="fa-home"></i><span>fa-home</span></label>
<label title="\f016"><i class="fa-file-o"></i><span>fa-file-o</span></label>
<label title="\f017"><i class="fa-clock-o"></i><span>fa-clock-o</span></label>
<label title="\f018"><i class="fa-road"></i><span>fa-road</span></label>
<label title="\f019"><i class="fa-download"></i><span>fa-download</span></label>
<label title="\f01a"><i class="fa-arrow-circle-o-down"></i><span>fa-arrow-circle-o-down</span></label>
<label title="\f01b"><i class="fa-arrow-circle-o-up"></i><span>fa-arrow-circle-o-up</span></label>
<label title="\f01c"><i class="fa-inbox"></i><span>fa-inbox</span></label>
<label title="\f01d"><i class="fa-play-circle-o"></i><span>fa-play-circle-o</span></label>
<label title="\f01e"><i class="fa-repeat"></i><span>fa-repeat</span></label>
<label title="\f021"><i class="fa-refresh"></i><span>fa-refresh</span></label>
<label title="\f022"><i class="fa-list-alt"></i><span>fa-list-alt</span></label>
<label title="\f023"><i class="fa-lock"></i><span>fa-lock</span></label>
<label title="\f024"><i class="fa-flag"></i><span>fa-flag</span></label>
<label title="\f025"><i class="fa-headphones"></i><span>fa-headphones</span></label>
<label title="\f026"><i class="fa-volume-off"></i><span>fa-volume-off</span></label>
<label title="\f027"><i class="fa-volume-down"></i><span>fa-volume-down</span></label>
<label title="\f028"><i class="fa-volume-up"></i><span>fa-volume-up</span></label>
<label title="\f029"><i class="fa-qrcode"></i><span>fa-qrcode</span></label>
<label title="\f02a"><i class="fa-barcode"></i><span>fa-barcode</span></label>
<label title="\f02b"><i class="fa-tag"></i><span>fa-tag</span></label>
<label title="\f02c"><i class="fa-tags"></i><span>fa-tags</span></label>
<label title="\f02d"><i class="fa-book"></i><span>fa-book</span></label>
<label title="\f02e"><i class="fa-bookmark"></i><span>fa-bookmark</span></label>
<label title="\f02f"><i class="fa-print"></i><span>fa-print</span></label>
<label title="\f030"><i class="fa-camera"></i><span>fa-camera</span></label>
<label title="\f031"><i class="fa-font"></i><span>fa-font</span></label>
<label title="\f032"><i class="fa-bold"></i><span>fa-bold</span></label>
<label title="\f033"><i class="fa-italic"></i><span>fa-italic</span></label>
<label title="\f034"><i class="fa-text-height"></i><span>fa-text-height</span></label>
<label title="\f035"><i class="fa-text-width"></i><span>fa-text-width</span></label>
<label title="\f036"><i class="fa-align-left"></i><span>fa-align-left</span></label>
<label title="\f037"><i class="fa-align-center"></i><span>fa-align-center</span></label>
<label title="\f038"><i class="fa-align-right"></i><span>fa-align-right</span></label>
<label title="\f039"><i class="fa-align-justify"></i><span>fa-align-justify</span></label>
<label title="\f03a"><i class="fa-list"></i><span>fa-list</span></label>
<label title="\f03b"><i class="fa-outdent"></i><span>fa-outdent</span></label>
<label title="\f03c"><i class="fa-indent"></i><span>fa-indent</span></label>
<label title="\f03d"><i class="fa-video-camera"></i><span>fa-video-camera</span></label>
<label title="\f03e"><i class="fa-picture-o"></i><span>fa-picture-o</span></label>
<label title="\f040"><i class="fa-pencil"></i><span>fa-pencil</span></label>
<label title="\f041"><i class="fa-map-marker"></i><span>fa-map-marker</span></label>
<label title="\f042"><i class="fa-adjust"></i><span>fa-adjust</span></label>
<label title="\f043"><i class="fa-tint"></i><span>fa-tint</span></label>
<label title="\f044"><i class="fa-pencil-square-o"></i><span>fa-pencil-square-o</span></label>
<label title="\f045"><i class="fa-share-square-o"></i><span>fa-share-square-o</span></label>
<label title="\f046"><i class="fa-check-square-o"></i><span>fa-check-square-o</span></label>
<label title="\f047"><i class="fa-arrows"></i><span>fa-arrows</span></label>
<label title="\f048"><i class="fa-step-backward"></i><span>fa-step-backward</span></label>
<label title="\f049"><i class="fa-fast-backward"></i><span>fa-fast-backward</span></label>
<label title="\f04a"><i class="fa-backward"></i><span>fa-backward</span></label>
<label title="\f04b"><i class="fa-play"></i><span>fa-play</span></label>
<label title="\f04c"><i class="fa-pause"></i><span>fa-pause</span></label>
<label title="\f04d"><i class="fa-stop"></i><span>fa-stop</span></label>
<label title="\f04e"><i class="fa-forward"></i><span>fa-forward</span></label>
<label title="\f050"><i class="fa-fast-forward"></i><span>fa-fast-forward</span></label>
<label title="\f051"><i class="fa-step-forward"></i><span>fa-step-forward</span></label>
<label title="\f052"><i class="fa-eject"></i><span>fa-eject</span></label>
<label title="\f053"><i class="fa-chevron-left"></i><span>fa-chevron-left</span></label>
<label title="\f054"><i class="fa-chevron-right"></i><span>fa-chevron-right</span></label>
<label title="\f055"><i class="fa-plus-circle"></i><span>fa-plus-circle</span></label>
<label title="\f056"><i class="fa-minus-circle"></i><span>fa-minus-circle</span></label>
<label title="\f057"><i class="fa-times-circle"></i><span>fa-times-circle</span></label>
<label title="\f058"><i class="fa-check-circle"></i><span>fa-check-circle</span></label>
<label title="\f059"><i class="fa-question-circle"></i><span>fa-question-circle</span></label>
<label title="\f05a"><i class="fa-info-circle"></i><span>fa-info-circle</span></label>
<label title="\f05b"><i class="fa-crosshairs"></i><span>fa-crosshairs</span></label>
<label title="\f05c"><i class="fa-times-circle-o"></i><span>fa-times-circle-o</span></label>
<label title="\f05d"><i class="fa-check-circle-o"></i><span>fa-check-circle-o</span></label>
<label title="\f05e"><i class="fa-ban"></i><span>fa-ban</span></label>
<label title="\f060"><i class="fa-arrow-left"></i><span>fa-arrow-left</span></label>
<label title="\f061"><i class="fa-arrow-right"></i><span>fa-arrow-right</span></label>
<label title="\f062"><i class="fa-arrow-up"></i><span>fa-arrow-up</span></label>
<label title="\f063"><i class="fa-arrow-down"></i><span>fa-arrow-down</span></label>
<label title="\f064"><i class="fa-share"></i><span>fa-share</span></label>
<label title="\f065"><i class="fa-expand"></i><span>fa-expand</span></label>
<label title="\f066"><i class="fa-compress"></i><span>fa-compress</span></label>
<label title="\f067"><i class="fa-plus"></i><span>fa-plus</span></label>
<label title="\f068"><i class="fa-minus"></i><span>fa-minus</span></label>
<label title="\f069"><i class="fa-asterisk"></i><span>fa-asterisk</span></label>
<label title="\f06a"><i class="fa-exclamation-circle"></i><span>fa-exclamation-circle</span></label>
<label title="\f06b"><i class="fa-gift"></i><span>fa-gift</span></label>
<label title="\f06c"><i class="fa-leaf"></i><span>fa-leaf</span></label>
<label title="\f06d"><i class="fa-fire"></i><span>fa-fire</span></label>
<label title="\f06e"><i class="fa-eye"></i><span>fa-eye</span></label>
<label title="\f070"><i class="fa-eye-slash"></i><span>fa-eye-slash</span></label>
<label title="\f071"><i class="fa-exclamation-triangle"></i><span>fa-exclamation-triangle</span></label>
<label title="\f072"><i class="fa-plane"></i><span>fa-plane</span></label>
<label title="\f073"><i class="fa-calendar"></i><span>fa-calendar</span></label>
<label title="\f074"><i class="fa-random"></i><span>fa-random</span></label>
<label title="\f075"><i class="fa-comment"></i><span>fa-comment</span></label>
<label title="\f076"><i class="fa-magnet"></i><span>fa-magnet</span></label>
<label title="\f077"><i class="fa-chevron-up"></i><span>fa-chevron-up</span></label>
<label title="\f078"><i class="fa-chevron-down"></i><span>fa-chevron-down</span></label>
<label title="\f079"><i class="fa-retweet"></i><span>fa-retweet</span></label>
<label title="\f07a"><i class="fa-shopping-cart"></i><span>fa-shopping-cart</span></label>
<label title="\f07b"><i class="fa-folder"></i><span>fa-folder</span></label>
<label title="\f07c"><i class="fa-folder-open"></i><span>fa-folder-open</span></label>
<label title="\f07d"><i class="fa-arrows-v"></i><span>fa-arrows-v</span></label>
<label title="\f07e"><i class="fa-arrows-h"></i><span>fa-arrows-h</span></label>
<label title="\f080"><i class="fa-bar-chart"></i><span>fa-bar-chart</span></label>
<label title="\f081"><i class="fa-twitter-square"></i><span>fa-twitter-square</span></label>
<label title="\f082"><i class="fa-facebook-square"></i><span>fa-facebook-square</span></label>
<label title="\f083"><i class="fa-camera-retro"></i><span>fa-camera-retro</span></label>
<label title="\f084"><i class="fa-key"></i><span>fa-key</span></label>
<label title="\f085"><i class="fa-cogs"></i><span>fa-cogs</span></label>
<label title="\f086"><i class="fa-comments"></i><span>fa-comments</span></label>
<label title="\f087"><i class="fa-thumbs-o-up"></i><span>fa-thumbs-o-up</span></label>
<label title="\f088"><i class="fa-thumbs-o-down"></i><span>fa-thumbs-o-down</span></label>
<label title="\f089"><i class="fa-star-half"></i><span>fa-star-half</span></label>
<label title="\f08a"><i class="fa-heart-o"></i><span>fa-heart-o</span></label>
<label title="\f08b"><i class="fa-sign-out"></i><span>fa-sign-out</span></label>
<label title="\f08c"><i class="fa-linkedin-square"></i><span>fa-linkedin-square</span></label>
<label title="\f08d"><i class="fa-thumb-tack"></i><span>fa-thumb-tack</span></label>
<label title="\f08e"><i class="fa-external-link"></i><span>fa-external-link</span></label>
<label title="\f090"><i class="fa-sign-in"></i><span>fa-sign-in</span></label>
<label title="\f091"><i class="fa-trophy"></i><span>fa-trophy</span></label>
<label title="\f092"><i class="fa-github-square"></i><span>fa-github-square</span></label>
<label title="\f093"><i class="fa-upload"></i><span>fa-upload</span></label>
<label title="\f094"><i class="fa-lemon-o"></i><span>fa-lemon-o</span></label>
<label title="\f095"><i class="fa-phone"></i><span>fa-phone</span></label>
<label title="\f096"><i class="fa-square-o"></i><span>fa-square-o</span></label>
<label title="\f097"><i class="fa-bookmark-o"></i><span>fa-bookmark-o</span></label>
<label title="\f098"><i class="fa-phone-square"></i><span>fa-phone-square</span></label>
<label title="\f099"><i class="fa-twitter"></i><span>fa-twitter</span></label>
<label title="\f09a"><i class="fa-facebook"></i><span>fa-facebook</span></label>
<label title="\f09b"><i class="fa-github"></i><span>fa-github</span></label>
<label title="\f09c"><i class="fa-unlock"></i><span>fa-unlock</span></label>
<label title="\f09d"><i class="fa-credit-card"></i><span>fa-credit-card</span></label>
<label title="\f09e"><i class="fa-rss"></i><span>fa-rss</span></label>
<label title="\f0a0"><i class="fa-hdd-o"></i><span>fa-hdd-o</span></label>
<label title="\f0a1"><i class="fa-bullhorn"></i><span>fa-bullhorn</span></label>
<label title="\f0f3"><i class="fa-bell"></i><span>fa-bell</span></label>
<label title="\f0a3"><i class="fa-certificate"></i><span>fa-certificate</span></label>
<label title="\f0a4"><i class="fa-hand-o-right"></i><span>fa-hand-o-right</span></label>
<label title="\f0a5"><i class="fa-hand-o-left"></i><span>fa-hand-o-left</span></label>
<label title="\f0a6"><i class="fa-hand-o-up"></i><span>fa-hand-o-up</span></label>
<label title="\f0a7"><i class="fa-hand-o-down"></i><span>fa-hand-o-down</span></label>
<label title="\f0a8"><i class="fa-arrow-circle-left"></i><span>fa-arrow-circle-left</span></label>
<label title="\f0a9"><i class="fa-arrow-circle-right"></i><span>fa-arrow-circle-right</span></label>
<label title="\f0aa"><i class="fa-arrow-circle-up"></i><span>fa-arrow-circle-up</span></label>
<label title="\f0ab"><i class="fa-arrow-circle-down"></i><span>fa-arrow-circle-down</span></label>
<label title="\f0ac"><i class="fa-globe"></i><span>fa-globe</span></label>
<label title="\f0ad"><i class="fa-wrench"></i><span>fa-wrench</span></label>
<label title="\f0ae"><i class="fa-tasks"></i><span>fa-tasks</span></label>
<label title="\f0b0"><i class="fa-filter"></i><span>fa-filter</span></label>
<label title="\f0b1"><i class="fa-briefcase"></i><span>fa-briefcase</span></label>
<label title="\f0b2"><i class="fa-arrows-alt"></i><span>fa-arrows-alt</span></label>
<label title="\f0c0"><i class="fa-users"></i><span>fa-users</span></label>
<label title="\f0c1"><i class="fa-link"></i><span>fa-link</span></label>
<label title="\f0c2"><i class="fa-cloud"></i><span>fa-cloud</span></label>
<label title="\f0c3"><i class="fa-flask"></i><span>fa-flask</span></label>
<label title="\f0c4"><i class="fa-scissors"></i><span>fa-scissors</span></label>
<label title="\f0c5"><i class="fa-files-o"></i><span>fa-files-o</span></label>
<label title="\f0c6"><i class="fa-paperclip"></i><span>fa-paperclip</span></label>
<label title="\f0c7"><i class="fa-floppy-o"></i><span>fa-floppy-o</span></label>
<label title="\f0c8"><i class="fa-square"></i><span>fa-square</span></label>
<label title="\f0c9"><i class="fa-bars"></i><span>fa-bars</span></label>
<label title="\f0ca"><i class="fa-list-ul"></i><span>fa-list-ul</span></label>
<label title="\f0cb"><i class="fa-list-ol"></i><span>fa-list-ol</span></label>
<label title="\f0cc"><i class="fa-strikethrough"></i><span>fa-strikethrough</span></label>
<label title="\f0cd"><i class="fa-underline"></i><span>fa-underline</span></label>
<label title="\f0ce"><i class="fa-table"></i><span>fa-table</span></label>
<label title="\f0d0"><i class="fa-magic"></i><span>fa-magic</span></label>
<label title="\f0d1"><i class="fa-truck"></i><span>fa-truck</span></label>
<label title="\f0d2"><i class="fa-pinterest"></i><span>fa-pinterest</span></label>
<label title="\f0d3"><i class="fa-pinterest-square"></i><span>fa-pinterest-square</span></label>
<label title="\f0d4"><i class="fa-google-plus-square"></i><span>fa-google-plus-square</span></label>
<label title="\f0d5"><i class="fa-google-plus"></i><span>fa-google-plus</span></label>
<label title="\f0d6"><i class="fa-money"></i><span>fa-money</span></label>
<label title="\f0d7"><i class="fa-caret-down"></i><span>fa-caret-down</span></label>
<label title="\f0d8"><i class="fa-caret-up"></i><span>fa-caret-up</span></label>
<label title="\f0d9"><i class="fa-caret-left"></i><span>fa-caret-left</span></label>
<label title="\f0da"><i class="fa-caret-right"></i><span>fa-caret-right</span></label>
<label title="\f0db"><i class="fa-columns"></i><span>fa-columns</span></label>
<label title="\f0dc"><i class="fa-sort"></i><span>fa-sort</span></label>
<label title="\f0dd"><i class="fa-sort-desc"></i><span>fa-sort-desc</span></label>
<label title="\f0de"><i class="fa-sort-asc"></i><span>fa-sort-asc</span></label>
<label title="\f0e0"><i class="fa-envelope"></i><span>fa-envelope</span></label>
<label title="\f0e1"><i class="fa-linkedin"></i><span>fa-linkedin</span></label>
<label title="\f0e2"><i class="fa-undo"></i><span>fa-undo</span></label>
<label title="\f0e3"><i class="fa-gavel"></i><span>fa-gavel</span></label>
<label title="\f0e4"><i class="fa-tachometer"></i><span>fa-tachometer</span></label>
<label title="\f0e5"><i class="fa-comment-o"></i><span>fa-comment-o</span></label>
<label title="\f0e6"><i class="fa-comments-o"></i><span>fa-comments-o</span></label>
<label title="\f0e7"><i class="fa-bolt"></i><span>fa-bolt</span></label>
<label title="\f0e8"><i class="fa-sitemap"></i><span>fa-sitemap</span></label>
<label title="\f0e9"><i class="fa-umbrella"></i><span>fa-umbrella</span></label>
<label title="\f0ea"><i class="fa-clipboard"></i><span>fa-clipboard</span></label>
<label title="\f0eb"><i class="fa-lightbulb-o"></i><span>fa-lightbulb-o</span></label>
<label title="\f0ec"><i class="fa-exchange"></i><span>fa-exchange</span></label>
<label title="\f0ed"><i class="fa-cloud-download"></i><span>fa-cloud-download</span></label>
<label title="\f0ee"><i class="fa-cloud-upload"></i><span>fa-cloud-upload</span></label>
<label title="\f0f0"><i class="fa-user-md"></i><span>fa-user-md</span></label>
<label title="\f0f1"><i class="fa-stethoscope"></i><span>fa-stethoscope</span></label>
<label title="\f0f2"><i class="fa-suitcase"></i><span>fa-suitcase</span></label>
<label title="\f0a2"><i class="fa-bell-o"></i><span>fa-bell-o</span></label>
<label title="\f0f4"><i class="fa-coffee"></i><span>fa-coffee</span></label>
<label title="\f0f5"><i class="fa-cutlery"></i><span>fa-cutlery</span></label>
<label title="\f0f6"><i class="fa-file-text-o"></i><span>fa-file-text-o</span></label>
<label title="\f0f7"><i class="fa-building-o"></i><span>fa-building-o</span></label>
<label title="\f0f8"><i class="fa-hospital-o"></i><span>fa-hospital-o</span></label>
<label title="\f0f9"><i class="fa-ambulance"></i><span>fa-ambulance</span></label>
<label title="\f0fa"><i class="fa-medkit"></i><span>fa-medkit</span></label>
<label title="\f0fb"><i class="fa-fighter-jet"></i><span>fa-fighter-jet</span></label>
<label title="\f0fc"><i class="fa-beer"></i><span>fa-beer</span></label>
<label title="\f0fd"><i class="fa-h-square"></i><span>fa-h-square</span></label>
<label title="\f0fe"><i class="fa-plus-square"></i><span>fa-plus-square</span></label>
<label title="\f100"><i class="fa-angle-double-left"></i><span>fa-angle-double-left</span></label>
<label title="\f101"><i class="fa-angle-double-right"></i><span>fa-angle-double-right</span></label>
<label title="\f102"><i class="fa-angle-double-up"></i><span>fa-angle-double-up</span></label>
<label title="\f103"><i class="fa-angle-double-down"></i><span>fa-angle-double-down</span></label>
<label title="\f104"><i class="fa-angle-left"></i><span>fa-angle-left</span></label>
<label title="\f105"><i class="fa-angle-right"></i><span>fa-angle-right</span></label>
<label title="\f106"><i class="fa-angle-up"></i><span>fa-angle-up</span></label>
<label title="\f107"><i class="fa-angle-down"></i><span>fa-angle-down</span></label>
<label title="\f108"><i class="fa-desktop"></i><span>fa-desktop</span></label>
<label title="\f109"><i class="fa-laptop"></i><span>fa-laptop</span></label>
<label title="\f10a"><i class="fa-tablet"></i><span>fa-tablet</span></label>
<label title="\f10b"><i class="fa-mobile"></i><span>fa-mobile</span></label>
<label title="\f10c"><i class="fa-circle-o"></i><span>fa-circle-o</span></label>
<label title="\f10d"><i class="fa-quote-left"></i><span>fa-quote-left</span></label>
<label title="\f10e"><i class="fa-quote-right"></i><span>fa-quote-right</span></label>
<label title="\f110"><i class="fa-spinner"></i><span>fa-spinner</span></label>
<label title="\f111"><i class="fa-circle"></i><span>fa-circle</span></label>
<label title="\f112"><i class="fa-reply"></i><span>fa-reply</span></label>
<label title="\f113"><i class="fa-github-alt"></i><span>fa-github-alt</span></label>
<label title="\f114"><i class="fa-folder-o"></i><span>fa-folder-o</span></label>
<label title="\f115"><i class="fa-folder-open-o"></i><span>fa-folder-open-o</span></label>
<label title="\f118"><i class="fa-smile-o"></i><span>fa-smile-o</span></label>
<label title="\f119"><i class="fa-frown-o"></i><span>fa-frown-o</span></label>
<label title="\f11a"><i class="fa-meh-o"></i><span>fa-meh-o</span></label>
<label title="\f11b"><i class="fa-gamepad"></i><span>fa-gamepad</span></label>
<label title="\f11c"><i class="fa-keyboard-o"></i><span>fa-keyboard-o</span></label>
<label title="\f11d"><i class="fa-flag-o"></i><span>fa-flag-o</span></label>
<label title="\f11e"><i class="fa-flag-checkered"></i><span>fa-flag-checkered</span></label>
<label title="\f120"><i class="fa-terminal"></i><span>fa-terminal</span></label>
<label title="\f121"><i class="fa-code"></i><span>fa-code</span></label>
<label title="\f122"><i class="fa-reply-all"></i><span>fa-reply-all</span></label>
<label title="\f123"><i class="fa-star-half-o"></i><span>fa-star-half-o</span></label>
<label title="\f124"><i class="fa-location-arrow"></i><span>fa-location-arrow</span></label>
<label title="\f125"><i class="fa-crop"></i><span>fa-crop</span></label>
<label title="\f126"><i class="fa-code-fork"></i><span>fa-code-fork</span></label>
<label title="\f127"><i class="fa-chain-broken"></i><span>fa-chain-broken</span></label>
<label title="\f128"><i class="fa-question"></i><span>fa-question</span></label>
<label title="\f129"><i class="fa-info"></i><span>fa-info</span></label>
<label title="\f12a"><i class="fa-exclamation"></i><span>fa-exclamation</span></label>
<label title="\f12b"><i class="fa-superscript"></i><span>fa-superscript</span></label>
<label title="\f12c"><i class="fa-subscript"></i><span>fa-subscript</span></label>
<label title="\f12d"><i class="fa-eraser"></i><span>fa-eraser</span></label>
<label title="\f12e"><i class="fa-puzzle-piece"></i><span>fa-puzzle-piece</span></label>
<label title="\f130"><i class="fa-microphone"></i><span>fa-microphone</span></label>
<label title="\f131"><i class="fa-microphone-slash"></i><span>fa-microphone-slash</span></label>
<label title="\f132"><i class="fa-shield"></i><span>fa-shield</span></label>
<label title="\f133"><i class="fa-calendar-o"></i><span>fa-calendar-o</span></label>
<label title="\f134"><i class="fa-fire-extinguisher"></i><span>fa-fire-extinguisher</span></label>
<label title="\f135"><i class="fa-rocket"></i><span>fa-rocket</span></label>
<label title="\f136"><i class="fa-maxcdn"></i><span>fa-maxcdn</span></label>
<label title="\f137"><i class="fa-chevron-circle-left"></i><span>fa-chevron-circle-left</span></label>
<label title="\f138"><i class="fa-chevron-circle-right"></i><span>fa-chevron-circle-right</span></label>
<label title="\f139"><i class="fa-chevron-circle-up"></i><span>fa-chevron-circle-up</span></label>
<label title="\f13a"><i class="fa-chevron-circle-down"></i><span>fa-chevron-circle-down</span></label>
<label title="\f13b"><i class="fa-html5"></i><span>fa-html5</span></label>
<label title="\f13c"><i class="fa-css3"></i><span>fa-css3</span></label>
<label title="\f13d"><i class="fa-anchor"></i><span>fa-anchor</span></label>
<label title="\f13e"><i class="fa-unlock-alt"></i><span>fa-unlock-alt</span></label>
<label title="\f140"><i class="fa-bullseye"></i><span>fa-bullseye</span></label>
<label title="\f141"><i class="fa-ellipsis-h"></i><span>fa-ellipsis-h</span></label>
<label title="\f142"><i class="fa-ellipsis-v"></i><span>fa-ellipsis-v</span></label>
<label title="\f143"><i class="fa-rss-square"></i><span>fa-rss-square</span></label>
<label title="\f144"><i class="fa-play-circle"></i><span>fa-play-circle</span></label>
<label title="\f145"><i class="fa-ticket"></i><span>fa-ticket</span></label>
<label title="\f146"><i class="fa-minus-square"></i><span>fa-minus-square</span></label>
<label title="\f147"><i class="fa-minus-square-o"></i><span>fa-minus-square-o</span></label>
<label title="\f148"><i class="fa-level-up"></i><span>fa-level-up</span></label>
<label title="\f149"><i class="fa-level-down"></i><span>fa-level-down</span></label>
<label title="\f14a"><i class="fa-check-square"></i><span>fa-check-square</span></label>
<label title="\f14b"><i class="fa-pencil-square"></i><span>fa-pencil-square</span></label>
<label title="\f14c"><i class="fa-external-link-square"></i><span>fa-external-link-square</span></label>
<label title="\f14d"><i class="fa-share-square"></i><span>fa-share-square</span></label>
<label title="\f14e"><i class="fa-compass"></i><span>fa-compass</span></label>
<label title="\f150"><i class="fa-caret-square-o-down"></i><span>fa-caret-square-o-down</span></label>
<label title="\f151"><i class="fa-caret-square-o-up"></i><span>fa-caret-square-o-up</span></label>
<label title="\f152"><i class="fa-caret-square-o-right"></i><span>fa-caret-square-o-right</span></label>
<label title="\f153"><i class="fa-eur"></i><span>fa-eur</span></label>
<label title="\f154"><i class="fa-gbp"></i><span>fa-gbp</span></label>
<label title="\f155"><i class="fa-usd"></i><span>fa-usd</span></label>
<label title="\f156"><i class="fa-inr"></i><span>fa-inr</span></label>
<label title="\f157"><i class="fa-jpy"></i><span>fa-jpy</span></label>
<label title="\f158"><i class="fa-rub"></i><span>fa-rub</span></label>
<label title="\f159"><i class="fa-krw"></i><span>fa-krw</span></label>
<label title="\f15a"><i class="fa-btc"></i><span>fa-btc</span></label>
<label title="\f15b"><i class="fa-file"></i><span>fa-file</span></label>
<label title="\f15c"><i class="fa-file-text"></i><span>fa-file-text</span></label>
<label title="\f15d"><i class="fa-sort-alpha-asc"></i><span>fa-sort-alpha-asc</span></label>
<label title="\f15e"><i class="fa-sort-alpha-desc"></i><span>fa-sort-alpha-desc</span></label>
<label title="\f160"><i class="fa-sort-amount-asc"></i><span>fa-sort-amount-asc</span></label>
<label title="\f161"><i class="fa-sort-amount-desc"></i><span>fa-sort-amount-desc</span></label>
<label title="\f162"><i class="fa-sort-numeric-asc"></i><span>fa-sort-numeric-asc</span></label>
<label title="\f163"><i class="fa-sort-numeric-desc"></i><span>fa-sort-numeric-desc</span></label>
<label title="\f164"><i class="fa-thumbs-up"></i><span>fa-thumbs-up</span></label>
<label title="\f165"><i class="fa-thumbs-down"></i><span>fa-thumbs-down</span></label>
<label title="\f166"><i class="fa-youtube-square"></i><span>fa-youtube-square</span></label>
<label title="\f167"><i class="fa-youtube"></i><span>fa-youtube</span></label>
<label title="\f168"><i class="fa-xing"></i><span>fa-xing</span></label>
<label title="\f169"><i class="fa-xing-square"></i><span>fa-xing-square</span></label>
<label title="\f16a"><i class="fa-youtube-play"></i><span>fa-youtube-play</span></label>
<label title="\f16b"><i class="fa-dropbox"></i><span>fa-dropbox</span></label>
<label title="\f16c"><i class="fa-stack-overflow"></i><span>fa-stack-overflow</span></label>
<label title="\f16d"><i class="fa-instagram"></i><span>fa-instagram</span></label>
<label title="\f16e"><i class="fa-flickr"></i><span>fa-flickr</span></label>
<label title="\f170"><i class="fa-adn"></i><span>fa-adn</span></label>
<label title="\f171"><i class="fa-bitbucket"></i><span>fa-bitbucket</span></label>
<label title="\f172"><i class="fa-bitbucket-square"></i><span>fa-bitbucket-square</span></label>
<label title="\f173"><i class="fa-tumblr"></i><span>fa-tumblr</span></label>
<label title="\f174"><i class="fa-tumblr-square"></i><span>fa-tumblr-square</span></label>
<label title="\f175"><i class="fa-long-arrow-down"></i><span>fa-long-arrow-down</span></label>
<label title="\f176"><i class="fa-long-arrow-up"></i><span>fa-long-arrow-up</span></label>
<label title="\f177"><i class="fa-long-arrow-left"></i><span>fa-long-arrow-left</span></label>
<label title="\f178"><i class="fa-long-arrow-right"></i><span>fa-long-arrow-right</span></label>
<label title="\f179"><i class="fa-apple"></i><span>fa-apple</span></label>
<label title="\f17a"><i class="fa-windows"></i><span>fa-windows</span></label>
<label title="\f17b"><i class="fa-android"></i><span>fa-android</span></label>
<label title="\f17c"><i class="fa-linux"></i><span>fa-linux</span></label>
<label title="\f17d"><i class="fa-dribbble"></i><span>fa-dribbble</span></label>
<label title="\f17e"><i class="fa-skype"></i><span>fa-skype</span></label>
<label title="\f180"><i class="fa-foursquare"></i><span>fa-foursquare</span></label>
<label title="\f181"><i class="fa-trello"></i><span>fa-trello</span></label>
<label title="\f182"><i class="fa-female"></i><span>fa-female</span></label>
<label title="\f183"><i class="fa-male"></i><span>fa-male</span></label>
<label title="\f184"><i class="fa-gratipay"></i><span>fa-gratipay</span></label>
<label title="\f185"><i class="fa-sun-o"></i><span>fa-sun-o</span></label>
<label title="\f186"><i class="fa-moon-o"></i><span>fa-moon-o</span></label>
<label title="\f187"><i class="fa-archive"></i><span>fa-archive</span></label>
<label title="\f188"><i class="fa-bug"></i><span>fa-bug</span></label>
<label title="\f189"><i class="fa-vk"></i><span>fa-vk</span></label>
<label title="\f18a"><i class="fa-weibo"></i><span>fa-weibo</span></label>
<label title="\f18b"><i class="fa-renren"></i><span>fa-renren</span></label>
<label title="\f18c"><i class="fa-pagelines"></i><span>fa-pagelines</span></label>
<label title="\f18d"><i class="fa-stack-exchange"></i><span>fa-stack-exchange</span></label>
<label title="\f18e"><i class="fa-arrow-circle-o-right"></i><span>fa-arrow-circle-o-right</span></label>
<label title="\f190"><i class="fa-arrow-circle-o-left"></i><span>fa-arrow-circle-o-left</span></label>
<label title="\f191"><i class="fa-caret-square-o-left"></i><span>fa-caret-square-o-left</span></label>
<label title="\f192"><i class="fa-dot-circle-o"></i><span>fa-dot-circle-o</span></label>
<label title="\f193"><i class="fa-wheelchair"></i><span>fa-wheelchair</span></label>
<label title="\f194"><i class="fa-vimeo-square"></i><span>fa-vimeo-square</span></label>
<label title="\f195"><i class="fa-try"></i><span>fa-try</span></label>
<label title="\f196"><i class="fa-plus-square-o"></i><span>fa-plus-square-o</span></label>
<label title="\f197"><i class="fa-space-shuttle"></i><span>fa-space-shuttle</span></label>
<label title="\f198"><i class="fa-slack"></i><span>fa-slack</span></label>
<label title="\f199"><i class="fa-envelope-square"></i><span>fa-envelope-square</span></label>
<label title="\f19a"><i class="fa-wordpress"></i><span>fa-wordpress</span></label>
<label title="\f19b"><i class="fa-openid"></i><span>fa-openid</span></label>
<label title="\f19c"><i class="fa-university"></i><span>fa-university</span></label>
<label title="\f19d"><i class="fa-graduation-cap"></i><span>fa-graduation-cap</span></label>
<label title="\f19e"><i class="fa-yahoo"></i><span>fa-yahoo</span></label>
<label title="\f1a0"><i class="fa-google"></i><span>fa-google</span></label>
<label title="\f1a1"><i class="fa-reddit"></i><span>fa-reddit</span></label>
<label title="\f1a2"><i class="fa-reddit-square"></i><span>fa-reddit-square</span></label>
<label title="\f1a3"><i class="fa-stumbleupon-circle"></i><span>fa-stumbleupon-circle</span></label>
<label title="\f1a4"><i class="fa-stumbleupon"></i><span>fa-stumbleupon</span></label>
<label title="\f1a5"><i class="fa-delicious"></i><span>fa-delicious</span></label>
<label title="\f1a6"><i class="fa-digg"></i><span>fa-digg</span></label>
<label title="\f1a7"><i class="fa-pied-piper-pp"></i><span>fa-pied-piper-pp</span></label>
<label title="\f1a8"><i class="fa-pied-piper-alt"></i><span>fa-pied-piper-alt</span></label>
<label title="\f1a9"><i class="fa-drupal"></i><span>fa-drupal</span></label>
<label title="\f1aa"><i class="fa-joomla"></i><span>fa-joomla</span></label>
<label title="\f1ab"><i class="fa-language"></i><span>fa-language</span></label>
<label title="\f1ac"><i class="fa-fax"></i><span>fa-fax</span></label>
<label title="\f1ad"><i class="fa-building"></i><span>fa-building</span></label>
<label title="\f1ae"><i class="fa-child"></i><span>fa-child</span></label>
<label title="\f1b0"><i class="fa-paw"></i><span>fa-paw</span></label>
<label title="\f1b1"><i class="fa-spoon"></i><span>fa-spoon</span></label>
<label title="\f1b2"><i class="fa-cube"></i><span>fa-cube</span></label>
<label title="\f1b3"><i class="fa-cubes"></i><span>fa-cubes</span></label>
<label title="\f1b4"><i class="fa-behance"></i><span>fa-behance</span></label>
<label title="\f1b5"><i class="fa-behance-square"></i><span>fa-behance-square</span></label>
<label title="\f1b6"><i class="fa-steam"></i><span>fa-steam</span></label>
<label title="\f1b7"><i class="fa-steam-square"></i><span>fa-steam-square</span></label>
<label title="\f1b8"><i class="fa-recycle"></i><span>fa-recycle</span></label>
<label title="\f1b9"><i class="fa-car"></i><span>fa-car</span></label>
<label title="\f1ba"><i class="fa-taxi"></i><span>fa-taxi</span></label>
<label title="\f1bb"><i class="fa-tree"></i><span>fa-tree</span></label>
<label title="\f1bc"><i class="fa-spotify"></i><span>fa-spotify</span></label>
<label title="\f1bd"><i class="fa-deviantart"></i><span>fa-deviantart</span></label>
<label title="\f1be"><i class="fa-soundcloud"></i><span>fa-soundcloud</span></label>
<label title="\f1c0"><i class="fa-database"></i><span>fa-database</span></label>
<label title="\f1c1"><i class="fa-file-pdf-o"></i><span>fa-file-pdf-o</span></label>
<label title="\f1c2"><i class="fa-file-word-o"></i><span>fa-file-word-o</span></label>
<label title="\f1c3"><i class="fa-file-excel-o"></i><span>fa-file-excel-o</span></label>
<label title="\f1c4"><i class="fa-file-powerpoint-o"></i><span>fa-file-powerpoint-o</span></label>
<label title="\f1c5"><i class="fa-file-image-o"></i><span>fa-file-image-o</span></label>
<label title="\f1c6"><i class="fa-file-archive-o"></i><span>fa-file-archive-o</span></label>
<label title="\f1c7"><i class="fa-file-audio-o"></i><span>fa-file-audio-o</span></label>
<label title="\f1c8"><i class="fa-file-video-o"></i><span>fa-file-video-o</span></label>
<label title="\f1c9"><i class="fa-file-code-o"></i><span>fa-file-code-o</span></label>
<label title="\f1ca"><i class="fa-vine"></i><span>fa-vine</span></label>
<label title="\f1cb"><i class="fa-codepen"></i><span>fa-codepen</span></label>
<label title="\f1cc"><i class="fa-jsfiddle"></i><span>fa-jsfiddle</span></label>
<label title="\f1cd"><i class="fa-life-ring"></i><span>fa-life-ring</span></label>
<label title="\f1ce"><i class="fa-circle-o-notch"></i><span>fa-circle-o-notch</span></label>
<label title="\f1d0"><i class="fa-rebel"></i><span>fa-rebel</span></label>
<label title="\f1d1"><i class="fa-empire"></i><span>fa-empire</span></label>
<label title="\f1d2"><i class="fa-git-square"></i><span>fa-git-square</span></label>
<label title="\f1d3"><i class="fa-git"></i><span>fa-git</span></label>
<label title="\f1d4"><i class="fa-hacker-news"></i><span>fa-hacker-news</span></label>
<label title="\f1d5"><i class="fa-tencent-weibo"></i><span>fa-tencent-weibo</span></label>
<label title="\f1d6"><i class="fa-qq"></i><span>fa-qq</span></label>
<label title="\f1d7"><i class="fa-weixin"></i><span>fa-weixin</span></label>
<label title="\f1d8"><i class="fa-paper-plane"></i><span>fa-paper-plane</span></label>
<label title="\f1d9"><i class="fa-paper-plane-o"></i><span>fa-paper-plane-o</span></label>
<label title="\f1da"><i class="fa-history"></i><span>fa-history</span></label>
<label title="\f1db"><i class="fa-circle-thin"></i><span>fa-circle-thin</span></label>
<label title="\f1dc"><i class="fa-header"></i><span>fa-header</span></label>
<label title="\f1dd"><i class="fa-paragraph"></i><span>fa-paragraph</span></label>
<label title="\f1de"><i class="fa-sliders"></i><span>fa-sliders</span></label>
<label title="\f1e0"><i class="fa-share-alt"></i><span>fa-share-alt</span></label>
<label title="\f1e1"><i class="fa-share-alt-square"></i><span>fa-share-alt-square</span></label>
<label title="\f1e2"><i class="fa-bomb"></i><span>fa-bomb</span></label>
<label title="\f1e3"><i class="fa-futbol-o"></i><span>fa-futbol-o</span></label>
<label title="\f1e4"><i class="fa-tty"></i><span>fa-tty</span></label>
<label title="\f1e5"><i class="fa-binoculars"></i><span>fa-binoculars</span></label>
<label title="\f1e6"><i class="fa-plug"></i><span>fa-plug</span></label>
<label title="\f1e7"><i class="fa-slideshare"></i><span>fa-slideshare</span></label>
<label title="\f1e8"><i class="fa-twitch"></i><span>fa-twitch</span></label>
<label title="\f1e9"><i class="fa-yelp"></i><span>fa-yelp</span></label>
<label title="\f1ea"><i class="fa-newspaper-o"></i><span>fa-newspaper-o</span></label>
<label title="\f1eb"><i class="fa-wifi"></i><span>fa-wifi</span></label>
<label title="\f1ec"><i class="fa-calculator"></i><span>fa-calculator</span></label>
<label title="\f1ed"><i class="fa-paypal"></i><span>fa-paypal</span></label>
<label title="\f1ee"><i class="fa-google-wallet"></i><span>fa-google-wallet</span></label>
<label title="\f1f0"><i class="fa-cc-visa"></i><span>fa-cc-visa</span></label>
<label title="\f1f1"><i class="fa-cc-mastercard"></i><span>fa-cc-mastercard</span></label>
<label title="\f1f2"><i class="fa-cc-discover"></i><span>fa-cc-discover</span></label>
<label title="\f1f3"><i class="fa-cc-amex"></i><span>fa-cc-amex</span></label>
<label title="\f1f4"><i class="fa-cc-paypal"></i><span>fa-cc-paypal</span></label>
<label title="\f1f5"><i class="fa-cc-stripe"></i><span>fa-cc-stripe</span></label>
<label title="\f1f6"><i class="fa-bell-slash"></i><span>fa-bell-slash</span></label>
<label title="\f1f7"><i class="fa-bell-slash-o"></i><span>fa-bell-slash-o</span></label>
<label title="\f1f8"><i class="fa-trash"></i><span>fa-trash</span></label>
<label title="\f1f9"><i class="fa-copyright"></i><span>fa-copyright</span></label>
<label title="\f1fa"><i class="fa-at"></i><span>fa-at</span></label>
<label title="\f1fb"><i class="fa-eyedropper"></i><span>fa-eyedropper</span></label>
<label title="\f1fc"><i class="fa-paint-brush"></i><span>fa-paint-brush</span></label>
<label title="\f1fd"><i class="fa-birthday-cake"></i><span>fa-birthday-cake</span></label>
<label title="\f1fe"><i class="fa-area-chart"></i><span>fa-area-chart</span></label>
<label title="\f200"><i class="fa-pie-chart"></i><span>fa-pie-chart</span></label>
<label title="\f201"><i class="fa-line-chart"></i><span>fa-line-chart</span></label>
<label title="\f202"><i class="fa-lastfm"></i><span>fa-lastfm</span></label>
<label title="\f203"><i class="fa-lastfm-square"></i><span>fa-lastfm-square</span></label>
<label title="\f204"><i class="fa-toggle-off"></i><span>fa-toggle-off</span></label>
<label title="\f205"><i class="fa-toggle-on"></i><span>fa-toggle-on</span></label>
<label title="\f206"><i class="fa-bicycle"></i><span>fa-bicycle</span></label>
<label title="\f207"><i class="fa-bus"></i><span>fa-bus</span></label>
<label title="\f208"><i class="fa-ioxhost"></i><span>fa-ioxhost</span></label>
<label title="\f209"><i class="fa-angellist"></i><span>fa-angellist</span></label>
<label title="\f20a"><i class="fa-cc"></i><span>fa-cc</span></label>
<label title="\f20b"><i class="fa-ils"></i><span>fa-ils</span></label>
<label title="\f20c"><i class="fa-meanpath"></i><span>fa-meanpath</span></label>
<label title="\f20d"><i class="fa-buysellads"></i><span>fa-buysellads</span></label>
<label title="\f20e"><i class="fa-connectdevelop"></i><span>fa-connectdevelop</span></label>
<label title="\f210"><i class="fa-dashcube"></i><span>fa-dashcube</span></label>
<label title="\f211"><i class="fa-forumbee"></i><span>fa-forumbee</span></label>
<label title="\f212"><i class="fa-leanpub"></i><span>fa-leanpub</span></label>
<label title="\f213"><i class="fa-sellsy"></i><span>fa-sellsy</span></label>
<label title="\f214"><i class="fa-shirtsinbulk"></i><span>fa-shirtsinbulk</span></label>
<label title="\f215"><i class="fa-simplybuilt"></i><span>fa-simplybuilt</span></label>
<label title="\f216"><i class="fa-skyatlas"></i><span>fa-skyatlas</span></label>
<label title="\f217"><i class="fa-cart-plus"></i><span>fa-cart-plus</span></label>
<label title="\f218"><i class="fa-cart-arrow-down"></i><span>fa-cart-arrow-down</span></label>
<label title="\f219"><i class="fa-diamond"></i><span>fa-diamond</span></label>
<label title="\f21a"><i class="fa-ship"></i><span>fa-ship</span></label>
<label title="\f21b"><i class="fa-user-secret"></i><span>fa-user-secret</span></label>
<label title="\f21c"><i class="fa-motorcycle"></i><span>fa-motorcycle</span></label>
<label title="\f21d"><i class="fa-street-view"></i><span>fa-street-view</span></label>
<label title="\f21e"><i class="fa-heartbeat"></i><span>fa-heartbeat</span></label>
<label title="\f221"><i class="fa-venus"></i><span>fa-venus</span></label>
<label title="\f222"><i class="fa-mars"></i><span>fa-mars</span></label>
<label title="\f223"><i class="fa-mercury"></i><span>fa-mercury</span></label>
<label title="\f224"><i class="fa-transgender"></i><span>fa-transgender</span></label>
<label title="\f225"><i class="fa-transgender-alt"></i><span>fa-transgender-alt</span></label>
<label title="\f226"><i class="fa-venus-double"></i><span>fa-venus-double</span></label>
<label title="\f227"><i class="fa-mars-double"></i><span>fa-mars-double</span></label>
<label title="\f228"><i class="fa-venus-mars"></i><span>fa-venus-mars</span></label>
<label title="\f229"><i class="fa-mars-stroke"></i><span>fa-mars-stroke</span></label>
<label title="\f22a"><i class="fa-mars-stroke-v"></i><span>fa-mars-stroke-v</span></label>
<label title="\f22b"><i class="fa-mars-stroke-h"></i><span>fa-mars-stroke-h</span></label>
<label title="\f22c"><i class="fa-neuter"></i><span>fa-neuter</span></label>
<label title="\f22d"><i class="fa-genderless"></i><span>fa-genderless</span></label>
<label title="\f230"><i class="fa-facebook-official"></i><span>fa-facebook-official</span></label>
<label title="\f231"><i class="fa-pinterest-p"></i><span>fa-pinterest-p</span></label>
<label title="\f232"><i class="fa-whatsapp"></i><span>fa-whatsapp</span></label>
<label title="\f233"><i class="fa-server"></i><span>fa-server</span></label>
<label title="\f234"><i class="fa-user-plus"></i><span>fa-user-plus</span></label>
<label title="\f235"><i class="fa-user-times"></i><span>fa-user-times</span></label>
<label title="\f236"><i class="fa-bed"></i><span>fa-bed</span></label>
<label title="\f237"><i class="fa-viacoin"></i><span>fa-viacoin</span></label>
<label title="\f238"><i class="fa-train"></i><span>fa-train</span></label>
<label title="\f239"><i class="fa-subway"></i><span>fa-subway</span></label>
<label title="\f23a"><i class="fa-medium"></i><span>fa-medium</span></label>
<label title="\f23b"><i class="fa-y-combinator"></i><span>fa-y-combinator</span></label>
<label title="\f23c"><i class="fa-optin-monster"></i><span>fa-optin-monster</span></label>
<label title="\f23d"><i class="fa-opencart"></i><span>fa-opencart</span></label>
<label title="\f23e"><i class="fa-expeditedssl"></i><span>fa-expeditedssl</span></label>
<label title="\f240"><i class="fa-battery-full"></i><span>fa-battery-full</span></label>
<label title="\f241"><i class="fa-battery-three-quarters"></i><span>fa-battery-three-quarters</span></label>
<label title="\f242"><i class="fa-battery-half"></i><span>fa-battery-half</span></label>
<label title="\f243"><i class="fa-battery-quarter"></i><span>fa-battery-quarter</span></label>
<label title="\f244"><i class="fa-battery-empty"></i><span>fa-battery-empty</span></label>
<label title="\f245"><i class="fa-mouse-pointer"></i><span>fa-mouse-pointer</span></label>
<label title="\f246"><i class="fa-i-cursor"></i><span>fa-i-cursor</span></label>
<label title="\f247"><i class="fa-object-group"></i><span>fa-object-group</span></label>
<label title="\f248"><i class="fa-object-ungroup"></i><span>fa-object-ungroup</span></label>
<label title="\f249"><i class="fa-sticky-note"></i><span>fa-sticky-note</span></label>
<label title="\f24a"><i class="fa-sticky-note-o"></i><span>fa-sticky-note-o</span></label>
<label title="\f24b"><i class="fa-cc-jcb"></i><span>fa-cc-jcb</span></label>
<label title="\f24c"><i class="fa-cc-diners-club"></i><span>fa-cc-diners-club</span></label>
<label title="\f24d"><i class="fa-clone"></i><span>fa-clone</span></label>
<label title="\f24e"><i class="fa-balance-scale"></i><span>fa-balance-scale</span></label>
<label title="\f250"><i class="fa-hourglass-o"></i><span>fa-hourglass-o</span></label>
<label title="\f251"><i class="fa-hourglass-start"></i><span>fa-hourglass-start</span></label>
<label title="\f252"><i class="fa-hourglass-half"></i><span>fa-hourglass-half</span></label>
<label title="\f253"><i class="fa-hourglass-end"></i><span>fa-hourglass-end</span></label>
<label title="\f254"><i class="fa-hourglass"></i><span>fa-hourglass</span></label>
<label title="\f255"><i class="fa-hand-rock-o"></i><span>fa-hand-rock-o</span></label>
<label title="\f256"><i class="fa-hand-paper-o"></i><span>fa-hand-paper-o</span></label>
<label title="\f257"><i class="fa-hand-scissors-o"></i><span>fa-hand-scissors-o</span></label>
<label title="\f258"><i class="fa-hand-lizard-o"></i><span>fa-hand-lizard-o</span></label>
<label title="\f259"><i class="fa-hand-spock-o"></i><span>fa-hand-spock-o</span></label>
<label title="\f25a"><i class="fa-hand-pointer-o"></i><span>fa-hand-pointer-o</span></label>
<label title="\f25b"><i class="fa-hand-peace-o"></i><span>fa-hand-peace-o</span></label>
<label title="\f25c"><i class="fa-trademark"></i><span>fa-trademark</span></label>
<label title="\f25d"><i class="fa-registered"></i><span>fa-registered</span></label>
<label title="\f25e"><i class="fa-creative-commons"></i><span>fa-creative-commons</span></label>
<label title="\f260"><i class="fa-gg"></i><span>fa-gg</span></label>
<label title="\f261"><i class="fa-gg-circle"></i><span>fa-gg-circle</span></label>
<label title="\f262"><i class="fa-tripadvisor"></i><span>fa-tripadvisor</span></label>
<label title="\f263"><i class="fa-odnoklassniki"></i><span>fa-odnoklassniki</span></label>
<label title="\f264"><i class="fa-odnoklassniki-square"></i><span>fa-odnoklassniki-square</span></label>
<label title="\f265"><i class="fa-get-pocket"></i><span>fa-get-pocket</span></label>
<label title="\f266"><i class="fa-wikipedia-w"></i><span>fa-wikipedia-w</span></label>
<label title="\f267"><i class="fa-safari"></i><span>fa-safari</span></label>
<label title="\f268"><i class="fa-chrome"></i><span>fa-chrome</span></label>
<label title="\f269"><i class="fa-firefox"></i><span>fa-firefox</span></label>
<label title="\f26a"><i class="fa-opera"></i><span>fa-opera</span></label>
<label title="\f26b"><i class="fa-internet-explorer"></i><span>fa-internet-explorer</span></label>
<label title="\f26c"><i class="fa-television"></i><span>fa-television</span></label>
<label title="\f26d"><i class="fa-contao"></i><span>fa-contao</span></label>
<label title="\f26e"><i class="fa-500px"></i><span>fa-500px</span></label>
<label title="\f270"><i class="fa-amazon"></i><span>fa-amazon</span></label>
<label title="\f271"><i class="fa-calendar-plus-o"></i><span>fa-calendar-plus-o</span></label>
<label title="\f272"><i class="fa-calendar-minus-o"></i><span>fa-calendar-minus-o</span></label>
<label title="\f273"><i class="fa-calendar-times-o"></i><span>fa-calendar-times-o</span></label>
<label title="\f274"><i class="fa-calendar-check-o"></i><span>fa-calendar-check-o</span></label>
<label title="\f275"><i class="fa-industry"></i><span>fa-industry</span></label>
<label title="\f276"><i class="fa-map-pin"></i><span>fa-map-pin</span></label>
<label title="\f277"><i class="fa-map-signs"></i><span>fa-map-signs</span></label>
<label title="\f278"><i class="fa-map-o"></i><span>fa-map-o</span></label>
<label title="\f279"><i class="fa-map"></i><span>fa-map</span></label>
<label title="\f27a"><i class="fa-commenting"></i><span>fa-commenting</span></label>
<label title="\f27b"><i class="fa-commenting-o"></i><span>fa-commenting-o</span></label>
<label title="\f27c"><i class="fa-houzz"></i><span>fa-houzz</span></label>
<label title="\f27d"><i class="fa-vimeo"></i><span>fa-vimeo</span></label>
<label title="\f27e"><i class="fa-black-tie"></i><span>fa-black-tie</span></label>
<label title="\f280"><i class="fa-fonticons"></i><span>fa-fonticons</span></label>
<label title="\f281"><i class="fa-reddit-alien"></i><span>fa-reddit-alien</span></label>
<label title="\f282"><i class="fa-edge"></i><span>fa-edge</span></label>
<label title="\f283"><i class="fa-credit-card-alt"></i><span>fa-credit-card-alt</span></label>
<label title="\f284"><i class="fa-codiepie"></i><span>fa-codiepie</span></label>
<label title="\f285"><i class="fa-modx"></i><span>fa-modx</span></label>
<label title="\f286"><i class="fa-fort-awesome"></i><span>fa-fort-awesome</span></label>
<label title="\f287"><i class="fa-usb"></i><span>fa-usb</span></label>
<label title="\f288"><i class="fa-product-hunt"></i><span>fa-product-hunt</span></label>
<label title="\f289"><i class="fa-mixcloud"></i><span>fa-mixcloud</span></label>
<label title="\f28a"><i class="fa-scribd"></i><span>fa-scribd</span></label>
<label title="\f28b"><i class="fa-pause-circle"></i><span>fa-pause-circle</span></label>
<label title="\f28c"><i class="fa-pause-circle-o"></i><span>fa-pause-circle-o</span></label>
<label title="\f28d"><i class="fa-stop-circle"></i><span>fa-stop-circle</span></label>
<label title="\f28e"><i class="fa-stop-circle-o"></i><span>fa-stop-circle-o</span></label>
<label title="\f290"><i class="fa-shopping-bag"></i><span>fa-shopping-bag</span></label>
<label title="\f291"><i class="fa-shopping-basket"></i><span>fa-shopping-basket</span></label>
<label title="\f292"><i class="fa-hashtag"></i><span>fa-hashtag</span></label>
<label title="\f293"><i class="fa-bluetooth"></i><span>fa-bluetooth</span></label>
<label title="\f294"><i class="fa-bluetooth-b"></i><span>fa-bluetooth-b</span></label>
<label title="\f295"><i class="fa-percent"></i><span>fa-percent</span></label>
<label title="\f296"><i class="fa-gitlab"></i><span>fa-gitlab</span></label>
<label title="\f297"><i class="fa-wpbeginner"></i><span>fa-wpbeginner</span></label>
<label title="\f298"><i class="fa-wpforms"></i><span>fa-wpforms</span></label>
<label title="\f299"><i class="fa-envira"></i><span>fa-envira</span></label>
<label title="\f29a"><i class="fa-universal-access"></i><span>fa-universal-access</span></label>
<label title="\f29b"><i class="fa-wheelchair-alt"></i><span>fa-wheelchair-alt</span></label>
<label title="\f29c"><i class="fa-question-circle-o"></i><span>fa-question-circle-o</span></label>
<label title="\f29d"><i class="fa-blind"></i><span>fa-blind</span></label>
<label title="\f29e"><i class="fa-audio-description"></i><span>fa-audio-description</span></label>
<label title="\f2a0"><i class="fa-volume-control-phone"></i><span>fa-volume-control-phone</span></label>
<label title="\f2a1"><i class="fa-braille"></i><span>fa-braille</span></label>
<label title="\f2a2"><i class="fa-assistive-listening-systems"></i><span>fa-assistive-listening-systems</span></label>
<label title="\f2a3"><i class="fa-american-sign-language-interpreting"></i><span>fa-american-sign-language-interpreting</span></label>
<label title="\f2a4"><i class="fa-deaf"></i><span>fa-deaf</span></label>
<label title="\f2a5"><i class="fa-glide"></i><span>fa-glide</span></label>
<label title="\f2a6"><i class="fa-glide-g"></i><span>fa-glide-g</span></label>
<label title="\f2a7"><i class="fa-sign-language"></i><span>fa-sign-language</span></label>
<label title="\f2a8"><i class="fa-low-vision"></i><span>fa-low-vision</span></label>
<label title="\f2a9"><i class="fa-viadeo"></i><span>fa-viadeo</span></label>
<label title="\f2aa"><i class="fa-viadeo-square"></i><span>fa-viadeo-square</span></label>
<label title="\f2ab"><i class="fa-snapchat"></i><span>fa-snapchat</span></label>
<label title="\f2ac"><i class="fa-snapchat-ghost"></i><span>fa-snapchat-ghost</span></label>
<label title="\f2ad"><i class="fa-snapchat-square"></i><span>fa-snapchat-square</span></label>
<label title="\f2ae"><i class="fa-pied-piper"></i><span>fa-pied-piper</span></label>
<label title="\f2b0"><i class="fa-first-order"></i><span>fa-first-order</span></label>
<label title="\f2b1"><i class="fa-yoast"></i><span>fa-yoast</span></label>
<label title="\f2b2"><i class="fa-themeisle"></i><span>fa-themeisle</span></label>
<label title="\f2b3"><i class="fa-google-plus-official"></i><span>fa-google-plus-official</span></label>
<label title="\f2b4"><i class="fa-font-awesome"></i><span>fa-font-awesome</span></label>

<!-- end -->
	</div>
</div>
</template>